    SET ROLE NHANVIENCOBAN;
    SELECT * FROM USERDBA.UV_SEL_NHANVIEN;
    UPDATE USERDBA.UV_SEL_NHANVIEN SET DT = '0987654321';
    SELECT * FROM USERDBA.DONVI;
    SELECT * FROM USERDBA.HOCPHAN;
    SELECT * FROM USERDBA.SINHVIEN;
    SELECT * FROM USERDBA.KHMO;
    SELECT * FROM USERDBA.DANGKY;