SET ROLE TRUONGDONVI;
    SELECT * FROM USERDBA.UV_SEL_NHANVIEN;
    UPDATE USERDBA.UV_SEL_NHANVIEN SET DT = '0369852147';
    SELECT * FROM USERDBA.DONVI;
    SELECT * FROM USERDBA.HOCPHAN;
    SELECT * FROM USERDBA.SINHVIEN;
    SELECT * FROM USERDBA.KHMO;
SELECT * FROM USERDBA.UV_SEL_GIANGVIEN_PHANCONG;  
SELECT * FROM USERDBA.UV_SEL_GIANGVIEN_DANGKY;
UPDATE SYS.UV_SEL_GIANGVIEN_DANGKY SET MAHP = 'HP002' WHERE MASV = 'SV2387';
UPDATE SYS.UV_SEL_GIANGVIEN_DANGKY SET DIEMTH = 9.2 WHERE MASV = 'SV238S7';
SELECT * FROM USERDBA.PHANCONG;
SELECT * FROM USERDBA.UV_TDV_MODIFY_PHANCONG;
DELETE FROM USERDBA.UV_TDV_MODIFY_PHANCONG WHERE MAGV = 'NV018' AND MAHP = 'HP007' AND HK = 3 AND NAM = 2024 AND MACT = 'CTTT';
INSERT INTO USERDBA.UV_TDV_MODIFY_PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('NV018', 'HP001', 2, 2024, 'CQ');
UPDATE USERDBA.UV_TDV_MODIFY_PHANCONG SET MAHP = 'HP007' WHERE MAGV = 'NV018' AND MAHP = 'HP001' AND HK = 2 AND NAM = 2024 AND MACT = 'CQ';
SELECT * FROM USERDBA.UV_TDV_XEM_PHANCONG_GIANGVIEN_CUA_DONVI;

SELECT * FROM USERDBA.THONGBAO;