SET ROLE TRUONGKHOA;
    SELECT * FROM USERDBA.UV_SEL_NHANVIEN;
    UPDATE USERDBA.UV_SEL_NHANVIEN SET DT = '0123456789';
    SELECT * FROM USERDBA.DONVI;
    SELECT * FROM USERDBA.HOCPHAN;
    SELECT * FROM USERDBA.SINHVIEN;
    SELECT * FROM USERDBA.KHMO;
SELECT * FROM USERDBA.UV_SEL_GIANGVIEN_PHANCONG;  
SELECT * FROM USERDBA.UV_SEL_GIANGVIEN_DANGKY;
UPDATE USERDBA.UV_SEL_GIANGVIEN_DANGKY SET MAHP = 'HP002' WHERE MASV = 'SV2387';
UPDATE USERDBA.UV_SEL_GIANGVIEN_DANGKY SET DIEMTH = 9.2 WHERE MASV = 'SV2387';

SELECT * FROM USERDBA.DANGKY;
SELECT * FROM USERDBA.PHANCONG;

INSERT INTO USERDBA.PHANCONG VALUES ('NV033', 'HP039', 1, 2024, 'CTTT');
INSERT INTO USERDBA.PHANCONG VALUES ('NV033', 'HP001', 1, 2024, 'CTTT');

UPDATE USERDBA.PHANCONG SET MACT = 'CQ' WHERE MAGV = 'NV033' AND MAHP = 'HP039' AND HK = 1 AND NAM = 2024 AND MACT = 'CTTT';
UPDATE USERDBA.PHANCONG SET MAGV = 'NV032' WHERE MAGV = 'NV033' AND MAHP = 'HP014' AND HK = 2 AND NAM = 2024 AND MACT = 'CLC';

DELETE FROM USERDBA.PHANCONG WHERE MAGV = 'NV033' AND MAHP = 'HP039' AND HK = 1 AND NAM = 2024 AND MACT = 'CQ';
DELETE FROM USERDBA.PHANCONG WHERE MAGV = 'NV018' AND MAHP = 'HP001' AND HK = 1 AND NAM = 2024 AND MACT = 'CLC';

SELECT * FROM USERDBA.NHANSU;

INSERT INTO USERDBA.NHANSU VALUES ('NV108', 'TEST_TRUONGKHOA', 'Nam', TO_DATE('2000-01-01', 'YYYY-MM-DD'), '1000', '01111111', N'Nhân viên cơ bản', 'DV006');
UPDATE USERDBA.NHANSU SET PHUCAP = '5000' WHERE MANV = 'NV108';
DELETE FROM USERDBA.NHANSU WHERE MANV = 'NV108';
UPDATE USERDBA.NHANSU SET PHUCAP = '5000' WHERE MANV = 'nv108';

select * from userdba.THONGBAO;